### ISSUE TITLE
Problemas con cabina de votación (Caso práctico de gestión de incidencias)

### ISSUE THREAD

**Issue by vladir291** [vladir291/Verification#18]
No podemos integrarnos de momento con cabina de votación debido a que su código está escrito en Python y nosotros ofrecemos una librería jar.

**Comment by jesusdaniel90** [comment]
Nos hemos reunido con el subgrupo cabina, y hemos llegado a un acuerdo en la solución del problema.

**Comment by vladir291** [comment]
Perfecto, cierro la incidencia.
